#!/bin/bash

# Script to verify all critical VS Code fork files and scripts are present

echo "🔍 Verifying VS Code Fork Repository Completeness..."
echo ""

ERRORS=0
WARNINGS=0

# Critical build files
echo "📦 Checking Critical Build Files..."
CRITICAL_FILES=(
    "package.json"
    "product.json"
    "electron-builder.yml"
    "gulpfile.js"
    "build/gulpfile.vscode.js"
    "build/gulpfile.compile.js"
    "build/lib/electron.js"
    "build/lib/preLaunch.js"
    "scripts/code.sh"
    "scripts/prepack.sh"
    "scripts/build_release.sh"
)

for file in "${CRITICAL_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "  ✅ $file"
    else
        echo "  ❌ MISSING: $file"
        ((ERRORS++))
    fi
done

echo ""
echo "🔧 Checking Build Scripts..."

# Check npm scripts
echo "  Checking package.json scripts..."
if grep -q "\"compile\"" package.json; then
    echo "    ✅ compile script"
else
    echo "    ❌ MISSING: compile script"
    ((ERRORS++))
fi

if grep -q "\"dist:mac\"" package.json; then
    echo "    ✅ dist:mac script"
else
    echo "    ❌ MISSING: dist:mac script"
    ((ERRORS++))
fi

if npm run | grep -q "gulp"; then
    echo "    ✅ gulp available"
else
    echo "    ⚠️  WARNING: gulp not available"
    ((WARNINGS++))
fi

echo ""
echo "📁 Checking Build Directories..."

BUILD_DIRS=(
    "build"
    "build/lib"
    "build/darwin"
    "build/linux"
    "build/win32"
    "scripts"
    "resources"
    "resources/darwin"
)

for dir in "${BUILD_DIRS[@]}"; do
    if [ -d "$dir" ]; then
        echo "  ✅ $dir/"
    else
        echo "  ⚠️  WARNING: $dir/ missing"
        ((WARNINGS++))
    fi
done

echo ""
echo "🎨 Checking Critical Source Files..."

SOURCE_FILES=(
    "src/main.ts"
    "src/vs/code/electron-browser/workbench/workbench.html"
    "src/vs/code/electron-browser/workbench/workbench.ts"
    "out/main.js"
)

for file in "${SOURCE_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "  ✅ $file"
    else
        if [[ "$file" == out/* ]]; then
            echo "  ⚠️  $file (will be generated during build)"
        else
            echo "  ❌ MISSING: $file"
            ((ERRORS++))
        fi
    fi
done

echo ""
echo "🔍 Checking for Common Missing Files..."

# Check for nls.messages.json
if [ -f "out/nls.messages.json" ]; then
    echo "  ✅ out/nls.messages.json (exists)"
else
    echo "  ⚠️  out/nls.messages.json (will be created by build script)"
fi

# Check for workbench CSS
if [ -f "out/vs/workbench/workbench.desktop.main.css" ]; then
    echo "  ✅ out/vs/workbench/workbench.desktop.main.css (exists)"
else
    echo "  ⚠️  out/vs/workbench/workbench.desktop.main.css (CRITICAL - must be generated by VS Code build)"
    echo "      This is why you're getting blank screen!"
    ((WARNINGS++))
fi

echo ""
echo "📋 Checking VS Code Build Tasks..."

if npm run gulp -- --tasks 2>&1 | grep -q "vscode-darwin"; then
    echo "  ✅ vscode-darwin build tasks available"
else
    echo "  ⚠️  WARNING: vscode-darwin tasks not found"
    ((WARNINGS++))
fi

if npm run gulp -- --tasks 2>&1 | grep -q "bundle-vscode"; then
    echo "  ✅ bundle-vscode task available"
else
    echo "  ⚠️  WARNING: bundle-vscode task not found"
    ((WARNINGS++))
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ $ERRORS -eq 0 ] && [ $WARNINGS -eq 0 ]; then
    echo "✅ All critical files and scripts are present!"
    echo "   Your repository appears complete."
    exit 0
elif [ $ERRORS -eq 0 ]; then
    echo "✅ All critical files present"
    echo "⚠️  $WARNINGS warning(s) - see above"
    echo ""
    echo "Most warnings are about generated files that will be created during build."
    exit 0
else
    echo "❌ $ERRORS critical file(s) missing!"
    echo "⚠️  $WARNINGS warning(s)"
    echo ""
    echo "Please fix the missing files before building."
    exit 1
fi







