directories:
  output: release
  buildResources: resources/darwin
appId: com.ren.renide
productName: Ren
files:
  - filter:
      - out/**/*
      - resources/**/*
      - .build/extensions/**/*
      - product.json
      - package.json
      - node_modules/**/*
      - '!**/node_modules/**/*.{md,ts,tsx,js.map}'
asar: true
asarUnpack:
  - '**/*.node'
  - '**/node_modules/@vscode/ripgrep/**'
  - '**/node_modules/node-pty/**'
  - .build/extensions/**
npmRebuild: true
mac:
  target:
    - dmg
  category: public.app-category.developer-tools
  icon: resources/darwin/code.icns
artifactName: ${productName}-${version}-${arch}.dmg
extraMetadata:
  main: ./out/main.js
electronVersion: 37.7.0
